site_name: "Calculation Tools Documentation"
site_url: "https://FNS-Division.github.io/calculation-tools_documentation/"
repo_url: "https://github.com/FNS-Division/calculation-tools_documentation"
theme:
  name: 'material'
  # Optional configuration for the Material theme
  features:
    - navigation.instant
    - search.highlight
    - toc.integrate  # Integrates Table of Contents in the sidebar
  
nav:
  - Home: index.md
  - Getting Started:
      - Prerequisites:
          - Old Version Prerequisites: old_version/prerequisites.md
          - Modified Version Prerequisites: modified_version/prerequisites.md
      - Setup:
          - Old Version Setup: old_version/setup.md
          - Modified Version Setup: modified_version/setup.md
  - Code Structure:
      - Overview: code_structure/overview.md
  - CI/CD Pipelines:
      - General Instructions: deployment/general.md
      - Azure DevOps Setup: deployment/azure_devops.md
      - AWS Deployment & Pipeline: deployment/aws_pipeline.md
  - Cloud Deployment:
      - Requirements: cloud/deployment_guide.md
      - Deploying on Azure: cloud/azure_deployment_guide.md
      - Deploying on AWS: cloud/aws_deployment_guide.md
      - Docker Setups: cloud/docker.md 
  - Usage:
      - Usage Examples: usage/old_version.md
  - Maintenance & Troubleshooting:
      - Maintenance Plan: maintenance/plan.md
      - Troubleshooting: maintenance/troubleshooting_guide.md
      - How to translate: maintenance/translating_guide.md
  - Contribution:
      - Guidelines: contribution/guidelines.md
  - Improvements:
      - Detailed Report on Proposed Improvements: improvements/report.md
  - Changelog: changelog.md

# Footer options, showing version or GitHub links
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/FNS-Division/calculation-tools_documentation
  copyright: "© 2024 FNS-Division. All rights reserved."

markdown_extensions:
  - toc:
      permalink: true  # Adds anchors to the Table of Contents for better navigation

# Enable search plugin (default)
plugins:
  - search
